### ISSUE TITLE
slash.js not loading...

### ISSUE THREAD

**Issue by iiMu7aMMaD** [meliooff/Structure-Discord-Bot#5]
PS C:\Users\iiMu7aMMaD\Desktop\master> node slash.js
[Discord API] Started refreshing application (/) commands.
w[20001]: Bots cannot use this endpoint
    at Z.runRequest (C:\Users\iiMu7aMMaD\Desktop\master\node_modules\@discordjs\rest\dist\index.js:7:581)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Z.queueRequest (C:\Users\iiMu7aMMaD\Desktop\master\node_modules\@discordjs\rest\dist\index.js:5:2989)
    at async C:\Users\iiMu7aMMaD\Desktop\master\slash.js:20:3 {
  rawError: { message: 'Bots cannot use this endpoint', code: 20001 },
  code: 20001,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v9/applications//commands',
  requestBody: { attachments: undefined, json: [ [Object] ] }
}

**Comment by antoinemcx** [comment]
Hi, how would you like us to help you without indicating anything ? You just throw an error like this at us, not a hello, not a description, nothing.
Anyways, you're probably using something that is no longer available on the Discord API, but once again we can't know since you only drop an error !
